services:
  - type: web
    name: pragatidesk-api
    runtime: node
    plan: free
    region: singapore
    rootDir: server
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 5050
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "file:./prisma/dev.db"
      - key: JWT_SECRET
        value: "pragatidesk_doitc_secret_key_2026_jwt_token_secure"
      - key: SMTP_HOST
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        value: "jitendra.jania@gmail.com"
      - key: SMTP_PASS
        value: "ubuh iebl qedx fkdt"
      - key: SMTP_FROM
        value: "PragatiDesk DoIT&C <jitendra.jania@gmail.com>"
