services:
  - type: web
    name: pragatidesk-api
    runtime: node
    plan: free
    region: singapore
    rootDir: server
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 5050
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "postgresql://pragatidesk_user:E09QcMMIdlsmGqfhgaaxgJZyqfDdizjn@dpg-dac0ilvqj5pc739j0fsg-a/pragatidesk"
      - key: JWT_SECRET
        value: "pragatidesk_doitc_secret_key_2026_jwt_token_secure"
      - key: SMTP_HOST
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "465"
      - key: SMTP_SECURE
        value: "true"
      - key: SMTP_USER
        value: "jitendra.jania@gmail.com"
      - key: SMTP_PASS
        value: "ubuhieblqedxfkdt"
      - key: SMTP_FROM
        value: "PragatiDesk (DoIT&C Rajasthan) <jitendra.jania@gmail.com>"
